export let SeriesLabels = {
  totalMonthlyPayment: "Total Cost",
  downpayment: "Downpayment",
  loanAmt: "Loan Amount",
  month: "Month",
  principal: "Principal",
  interest: "Interest",
  emi: "EMI",
  pmi: "PMI",
  propertyTax: "Property Tax",
  homeInsuranceCost: "Home Insurance Cost",
  hoaMonthly: "HOA Fee",
  maintainanceCost: "Maintainance Cost",
  otherCosts: "Other Costs",
  homeValueAppreciatedAmt: "Home Appreciated Amount",
  buyerClosingCost: "Buyer Closing Costs",
  closingCostAtSold: "Selling Closing Costs",
  netBuyingCost: "Net Buying Cost",
  netBuyingCostPerMonthAVG: "Net Buying Cost Average",
  cashAvailableForInvesting: "Cash Available after investing",
  loanBalance: "Loan Balance",
  taxSavings: "Tax Saving",
  rentalCost: "Rental Cost",
  returnOnInvestment: "Return on Investment",
  netInvestingToBuyingDifference: "Net Investing to Buying Difference ",
  price: 'Price',
  downpaymentPer: 'Downpayment %',
  apr: 'APR'
}
