export let SeriesLabels = {
  totalCost: "Total Cost",
  downpayment: "Downpayment",
  loanAmt: "Loan Amount",
  month: "Month",
  principal: "Principal",
  interest: "Interest",
  emi: "EMI",
  pmi: "PMI",
  propertyTax: "Property Tax",
  homeInsuranceCost: "Home Insurance Cost",
  hoaMonthly: "HOA Fee",
  maintainanceCost: "Maintainance Cost",
  otherCosts: "Other Costs",
  homeAppreciatedAmt: "Home Appreciated Amount",
  buyerClosingCost: "Buyer Closing Costs",
  closingCost: "Selling Closing Costs",
  actualBuyingCost: "Actual Buying Cost",
  actualBuyingCostPerMonthAVG: "Actual Buying Cost Average",
  buyingVsRentingDiff: "Buying Vs Renting Savings",
  rentingAvailableCash: "Renting Available Cash",
  loanBalance: "Loan Balance",
  taxSavings: "Tax Saving",
  rentalCost: "Rental Cost",
  oppertunityCost: "Oppertunity Cost",
  nettBuyingVsInvestingDiff: "Buying Vs Investing Savings",
  price: 'Price',
  downpaymentPer: 'Downpayment %',
  apr: 'APR'
}
